### ISSUE TITLE
RoR Recipe App: Set up of Project Kaban board Completed

### ISSUE THREAD

**Issue by ometman** [yusufyusie/recipe_app#25]
We have completed setting up the project Kanban board.
- We are  2-member team, that is @ometman and @yusufyusie 
- Link to project kanban:  https://github.com/yusufyusie/recipe_app/projects/4
- Link to the project: https://github.com/yusufyusie/recipe_app

**Comment by IngDavidTM** [comment]
## Hi Team 🙋‍♂️, 

Good job so far!
You have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the project but you are almost there!

<img src="https://media2.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Top highlight 🎯
- All the cards were assigned ✅

## Suggested changes


- [ ] Although your performance was impressive, it's necessary to include a description for each card you create, outlining your intended actions 👍.

![IMG_3095](https://github.com/yusufyusie/recipe_app/assets/105117832/bf8f82f8-0487-40a4-84ca-2a65b60b9a47)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ometman** [comment]
Thank you. All descriptions left out have been added. 😄

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @ometman and @yusufyusie,

✔️ Descriptive tasks

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
